docker-compose-yaml: docker-compose.yml
project: yukon-recruitment-marketing-drupal
environment_variables:
  git_sha: true

tasks:
  pre-rollout:
    - run:
        name: drush sql-dump
        command: |
          mkdir -p /app/private/deploy-backup/ && drush sql-dump --ordered-dump --gzip --result-file=/app/private/deploy-backup/pre-deploy-dump.sql.gz || true
        service: cli
  post-rollout:
    - run:
        name: Sync DB and Files from production if we are not on production
        command: |
          # Only if we don't have a database yet
          if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then
              drush sql-sync @lagoon.production @self -y
              drush rsync @lagoon.production:%files @self:%files -- --omit-dir-times --no-perms --no-group --no-owner --chmod=ugo=rwX
          fi
        service: cli
        when: LAGOON_ENVIRONMENT_TYPE != "production"
    - run:
        name: drush cr
        command: drush cr
        service: cli
    - run:
        name: drush updb
        command: drush updb -y
        service: cli
    - run:
        name: drush cim
        command: drush cim -y
        service: cli
    - run:
        name: drush cr
        command: drush cr
        service: cli

environments:
  master:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
