<?php

/**
 * @file
 * Primary module hooks for GYOCF Visualization module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function gyocf_visualization_theme() {
  return [
    'gyocf_lead' => [
      'render element' => 'elements',
    ],
    'gyocf_goal' => [
      'render element' => 'elements',
    ],
    'gyocf_objective' => [
      'render element' => 'elements',
    ],
    'gyocf_area' => [
      'render element' => 'elements',
    ],
    'gyocf_action' => [
      'render element' => 'elements',
    ],
    'gyocf_indicator' => [
      'render element' => 'elements',
    ],
    'gyocf_indicator_entry' => [
      'render element' => 'elements',
    ],
    'gyocf_directors_committee' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for lead templates.
 *
 * Default template: gyocf-lead.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the lead information
 *      and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_lead(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for goal templates.
 *
 * Default template: gyocf-goal.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the goal information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_goal(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for objective templates.
 *
 * Default template: gyocf-objective.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the objective information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_objective(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for area templates.
 *
 * Default template: gyocf-area.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the area information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_area(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for action templates.
 *
 * Default template: gyocf-action.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the action information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_action(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for indicator templates.
 *
 * Default template: gyocf-indicator.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the indicator information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_indicator(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for indicator entry templates.
 *
 * Default template: gyocf-indicator-entry.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the indicator entry information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_indicator_entry(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for directors committee templates.
 *
 * Default template: gyocf-directors-committee.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the directors committee
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_gyocf_directors_committee(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
