<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_page_form_alter().
 */
function govt_yukon_claro_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'node_page_edit_form' ||
    $form_id == 'node_page_form' ||
    $form_id == 'block_component_block_form' ||
    $form_id == 'block_section_block_form') {
    $form['#attached']['library'][] = 'govt_yukon/global-fonts';
    $form['#attached']['library'][] = 'govt_yukon/font-awesome';
  }
}
